{
  "swagger": "2.0",
  "basePath": "/api/v1",
  "info": {
    "title": "ToDo List API",
    "version": "v1"
  },
  "produces": [
    "application/vnd.api+json"
  ],
  "consumes": [
    "application/vnd.api+json"
  ],
  "securityDefinitions": {
    "access_token": {
      "type": "apiKey",
      "in": "header",
      "name": "access-token"
    },
    "token_type": {
      "type": "apiKey",
      "in": "header",
      "name": "token-type"
    },
    "client": {
      "type": "apiKey",
      "in": "header",
      "name": "client"
    },
    "uid": {
      "type": "apiKey",
      "in": "header",
      "name": "uid"
    }
  },
  "security": [
    {
      "access_token": [

      ],
      "token_type": [

      ],
      "client": [

      ],
      "uid": [

      ]
    }
  ],
  "paths": {
    "/tasks/{task_id}/comments": {
      "get": {
        "summary": "A list of Comment",
        "tags": [
          "Comments"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "task_id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A list of Comment",
            "examples": {
              "application/json": {
                "data": [
                  {
                    "id": "113",
                    "type": "comment",
                    "attributes": {
                      "body": "Body number_1",
                      "file": {
                        "name": "file",
                        "record": {
                          "id": 113,
                          "body": "Body number_1",
                          "created_at": "2019-11-04T10:08:09.125Z",
                          "updated_at": "2019-11-04T10:08:09.125Z",
                          "task_id": 967
                        }
                      }
                    },
                    "relationships": {
                      "task": {
                        "data": {
                          "id": "967",
                          "type": "task"
                        }
                      }
                    }
                  },
                  {
                    "id": "114",
                    "type": "comment",
                    "attributes": {
                      "body": "Body number_2",
                      "file": {
                        "name": "file",
                        "record": {
                          "id": 114,
                          "body": "Body number_2",
                          "created_at": "2019-11-04T10:08:09.129Z",
                          "updated_at": "2019-11-04T10:08:09.129Z",
                          "task_id": 967
                        }
                      }
                    },
                    "relationships": {
                      "task": {
                        "data": {
                          "id": "967",
                          "type": "task"
                        }
                      }
                    }
                  }
                ]
              }
            }
          },
          "401": {
            "description": "not authorized",
            "examples": {
              "application/json": {
                "errors": [
                  "You need to sign in or sign up before continuing."
                ]
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a Comment",
        "tags": [
          "Comments"
        ],
        "parameters": [
          {
            "name": "task_id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/comment"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "create a Comment",
            "examples": {
              "application/json": {
                "data": {
                  "id": "115",
                  "type": "comment",
                  "attributes": {
                    "body": "new comment",
                    "file": {
                      "name": "file",
                      "record": {
                        "id": 115,
                        "body": "new comment",
                        "created_at": "2019-11-04T10:08:09.580Z",
                        "updated_at": "2019-11-04T10:08:09.580Z",
                        "task_id": 969
                      }
                    }
                  },
                  "relationships": {
                    "task": {
                      "data": {
                        "id": "969",
                        "type": "task"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "wrong params",
            "examples": {
              "application/json": {
                "error": "Bad request"
              }
            }
          }
        }
      }
    },
    "/comments/{id}": {
      "delete": {
        "summary": "Delete the Comment",
        "tags": [
          "Comments"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "deleted comment"
          },
          "401": {
            "description": "not authorized",
            "examples": {
              "application/json": {
                "errors": [
                  "You need to sign in or sign up before continuing."
                ]
              }
            }
          }
        }
      }
    },
    "/tasks/{id}/complete": {
      "patch": {
        "summary": "Mark Task as complete",
        "tags": [
          "Task: Complete"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "task": {
                  "type": "object",
                  "properties": {
                    "done": {
                      "type": "boolean",
                      "example": "true"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "update Task complete",
            "examples": {
              "application/json": {
                "data": {
                  "id": "972",
                  "type": "task",
                  "attributes": {
                    "name": "Name_6",
                    "deadline": null,
                    "position": 1,
                    "done": true
                  },
                  "relationships": {
                    "project": {
                      "data": {
                        "id": "1086",
                        "type": "project"
                      }
                    },
                    "comments": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "invalid params",
            "examples": {
              "application/json": {
                "errors": [

                ]
              }
            }
          }
        }
      }
    },
    "/tasks/{id}/position": {
      "patch": {
        "summary": "Change Position of Task",
        "tags": [
          "Task: Position"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "task": {
                  "type": "object",
                  "properties": {
                    "position": {
                      "type": "integer",
                      "example": "0"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "update Task position",
            "examples": {
              "application/json": {
                "data": {
                  "id": "974",
                  "type": "task",
                  "attributes": {
                    "name": "Name_8",
                    "deadline": null,
                    "position": 4,
                    "done": false
                  },
                  "relationships": {
                    "project": {
                      "data": {
                        "id": "1088",
                        "type": "project"
                      }
                    },
                    "comments": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "invalid params",
            "examples": {
              "application/json": {
                "errors": [

                ]
              }
            }
          }
        }
      }
    },
    "/projects": {
      "get": {
        "summary": "A list of Projects",
        "tags": [
          "Projects"
        ],
        "responses": {
          "200": {
            "description": "A list of Projects",
            "examples": {
              "application/json": {
                "data": [
                  {
                    "id": "1090",
                    "type": "project",
                    "attributes": {
                      "name": "Name_10"
                    },
                    "relationships": {
                      "user": {
                        "data": {
                          "id": "1227",
                          "type": "user"
                        }
                      },
                      "tasks": {
                        "data": [

                        ]
                      }
                    }
                  },
                  {
                    "id": "1091",
                    "type": "project",
                    "attributes": {
                      "name": "Name_11"
                    },
                    "relationships": {
                      "user": {
                        "data": {
                          "id": "1227",
                          "type": "user"
                        }
                      },
                      "tasks": {
                        "data": [

                        ]
                      }
                    }
                  }
                ]
              }
            }
          },
          "401": {
            "description": "not authorized",
            "examples": {
              "application/json": {
                "errors": [
                  "You need to sign in or sign up before continuing."
                ]
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a Project",
        "tags": [
          "Projects"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/project"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Create a Project",
            "examples": {
              "application/json": {
                "data": {
                  "id": "1092",
                  "type": "project",
                  "attributes": {
                    "name": "Project"
                  },
                  "relationships": {
                    "user": {
                      "data": {
                        "id": "1228",
                        "type": "user"
                      }
                    },
                    "tasks": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "wrong params",
            "examples": {
              "application/json": {
                "error": "Bad request"
              }
            }
          }
        }
      }
    },
    "/projects/{id}": {
      "get": {
        "summary": "Shows a Project",
        "tags": [
          "Projects"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A Project",
            "examples": {
              "application/json": {
                "data": {
                  "id": "1093",
                  "type": "project",
                  "attributes": {
                    "name": "Name_12"
                  },
                  "relationships": {
                    "user": {
                      "data": {
                        "id": "1230",
                        "type": "user"
                      }
                    },
                    "tasks": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "not authorized",
            "examples": {
              "application/json": {
                "errors": [
                  "You need to sign in or sign up before continuing."
                ]
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update a Project",
        "tags": [
          "Projects"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/project"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update the Project",
            "examples": {
              "application/json": {
                "data": {
                  "id": "1094",
                  "type": "project",
                  "attributes": {
                    "name": "New Project"
                  },
                  "relationships": {
                    "user": {
                      "data": {
                        "id": "1231",
                        "type": "user"
                      }
                    },
                    "tasks": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete the Project",
        "tags": [
          "Projects"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "deleted project"
          },
          "401": {
            "description": "not authorized",
            "examples": {
              "application/json": {
                "errors": [
                  "You need to sign in or sign up before continuing."
                ]
              }
            }
          }
        }
      }
    },
    "/projects/{project_id}/tasks": {
      "get": {
        "summary": "A list of Tasks",
        "tags": [
          "Tasks"
        ],
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A list of Tasks",
            "examples": {
              "application/json": {
                "data": [
                  {
                    "id": "976",
                    "type": "task",
                    "attributes": {
                      "name": "Name_10",
                      "deadline": null,
                      "position": 1,
                      "done": false
                    },
                    "relationships": {
                      "project": {
                        "data": {
                          "id": "1096",
                          "type": "project"
                        }
                      },
                      "comments": {
                        "data": [

                        ]
                      }
                    }
                  },
                  {
                    "id": "978",
                    "type": "task",
                    "attributes": {
                      "name": "Name_12",
                      "deadline": null,
                      "position": 2,
                      "done": false
                    },
                    "relationships": {
                      "project": {
                        "data": {
                          "id": "1096",
                          "type": "project"
                        }
                      },
                      "comments": {
                        "data": [

                        ]
                      }
                    }
                  },
                  {
                    "id": "979",
                    "type": "task",
                    "attributes": {
                      "name": "Name_13",
                      "deadline": null,
                      "position": 3,
                      "done": false
                    },
                    "relationships": {
                      "project": {
                        "data": {
                          "id": "1096",
                          "type": "project"
                        }
                      },
                      "comments": {
                        "data": [

                        ]
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a Task",
        "tags": [
          "Tasks"
        ],
        "parameters": [
          {
            "name": "project_id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/task"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "create a Task",
            "examples": {
              "application/json": {
                "data": {
                  "id": "982",
                  "type": "task",
                  "attributes": {
                    "name": "Project",
                    "deadline": null,
                    "position": 2,
                    "done": false
                  },
                  "relationships": {
                    "project": {
                      "data": {
                        "id": "1098",
                        "type": "project"
                      }
                    },
                    "comments": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "invalid params",
            "examples": {
              "application/json": {
                "error": "Bad request"
              }
            }
          }
        }
      }
    },
    "/tasks/{id}": {
      "get": {
        "summary": "Show the Task",
        "tags": [
          "Tasks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "show a Task",
            "examples": {
              "application/json": {
                "data": {
                  "id": "985",
                  "type": "task",
                  "attributes": {
                    "name": "Name_18",
                    "deadline": null,
                    "position": 1,
                    "done": false
                  },
                  "relationships": {
                    "project": {
                      "data": {
                        "id": "1102",
                        "type": "project"
                      }
                    },
                    "comments": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "unauthorized",
            "examples": {
              "application/json": {
                "error": "Access Denied"
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update a Task",
        "tags": [
          "Tasks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "task": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "example": "string"
                    },
                    "deadline": {
                      "type": "datetime",
                      "example": "2019-09-22"
                    }
                  }
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Update the Task",
            "examples": {
              "application/json": {
                "data": {
                  "id": "989",
                  "type": "task",
                  "attributes": {
                    "name": "New Task",
                    "deadline": null,
                    "position": 1,
                    "done": false
                  },
                  "relationships": {
                    "project": {
                      "data": {
                        "id": "1106",
                        "type": "project"
                      }
                    },
                    "comments": {
                      "data": [

                      ]
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "unauthorized",
            "examples": {
              "application/json": {
                "error": "Access Denied"
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete the Task",
        "tags": [
          "Tasks"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "deleted task"
          },
          "403": {
            "description": "unauthorized",
            "examples": {
              "application/json": {
                "error": "Access Denied"
              }
            }
          }
        }
      }
    },
    "/auth/sign_in": {
      "post": {
        "summary": "Sign In",
        "tags": [
          "Authentication"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Sign In",
            "examples": {
              "application/json": {
                "data": {
                  "id": 1251,
                  "email": "person_34@example.com",
                  "provider": "email",
                  "uid": "person_34@example.com"
                }
              }
            }
          },
          "401": {
            "description": "Invalid login credentials",
            "examples": {
              "application/json": {
                "success": false,
                "errors": [
                  "Invalid login credentials. Please try again."
                ]
              }
            }
          }
        }
      }
    },
    "/auth/sign_out": {
      "delete": {
        "summary": "Sign Out",
        "tags": [
          "Authentication"
        ],
        "parameters": [
          {
            "name": "access-token",
            "in": "header",
            "type": "string"
          },
          {
            "name": "client",
            "in": "header",
            "type": "string"
          },
          {
            "name": "uid",
            "in": "header",
            "type": "string"
          },
          {
            "name": "token_type",
            "in": "header",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Sign Out",
            "examples": {
              "application/json": {
                "success": true
              }
            }
          },
          "404": {
            "description": "User was not found or was not logged in",
            "examples": {
              "application/json": {
                "success": false,
                "errors": [
                  "User was not found or was not logged in."
                ]
              }
            }
          }
        }
      }
    },
    "/auth": {
      "post": {
        "summary": "Registration",
        "tags": [
          "Authentication"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                },
                "password_confirmation": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Registration",
            "examples": {
              "application/json": {
                "status": "success",
                "data": {
                  "id": 1255,
                  "provider": "email",
                  "uid": "person_38@example.com",
                  "email": "person_38@example.com",
                  "created_at": "2019-11-04T10:08:15.968Z",
                  "updated_at": "2019-11-04T10:08:15.973Z"
                }
              }
            }
          },
          "422": {
            "description": "Invalid request",
            "examples": {
              "application/json": {
                "status": "error",
                "data": {
                  "id": null,
                  "provider": "email",
                  "uid": "",
                  "email": "1111",
                  "created_at": null,
                  "updated_at": null
                },
                "errors": {
                  "email": [
                    "is not an email"
                  ],
                  "full_messages": [
                    "Email is not an email"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "comment": {
      "type": "object",
      "properties": {
        "comment": {
          "type": "object",
          "required": [
            "body"
          ],
          "properties": {
            "body": {
              "type": "text",
              "example": "text"
            },
            "image": {
              "type": "string",
              "example": "image"
            }
          }
        }
      }
    },
    "task": {
      "type": "object",
      "properties": {
        "task": {
          "type": "object",
          "required": [
            "name"
          ],
          "properties": {
            "name": {
              "type": "string",
              "example": "string"
            },
            "deadline": {
              "type": "datetime",
              "example": "null"
            },
            "position": {
              "type": "integer",
              "example": "0"
            },
            "done": {
              "type": "boolean",
              "example": "false"
            }
          }
        }
      }
    },
    "project": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "project": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "example": "string"
            }
          }
        }
      }
    }
  }
}